services:
  django:
    container_name: thesis-langmodels-project-management
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DATABASE_URL=sqlite:///db.sqlite3
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py seed_static &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
