# Generated by Django 4.2.19 on 2025-02-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0001_initial'),
        ('ai_documentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aidocument',
            name='ai_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_models.aimodel'),
        ),
        migrations.DeleteModel(
            name='AIModel',
        ),
    ]
