# Generated by Django 4.2.19 on 2025-03-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_documentation', '0002_alter_aidocument_ai_model_delete_aimodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('prompt', models.TextField()),
                ('dependencies', models.ManyToManyField(blank=True, to='ai_documentation.documentsection')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_documentation.documenttype')),
            ],
        ),
    ]
