# Generated by Django 4.2.19 on 2025-02-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('model_identifier', models.CharField(max_length=255, unique=True)),
                ('file_path', models.FileField(upload_to='ai_models/storage/')),
            ],
        ),
    ]
