# Generated by Django 4.2.19 on 2025-02-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='file_path',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='local_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
