# Generated by Django 4.2.19 on 2025-02-16 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_models', '0002_remove_aimodel_file_path_aimodel_local_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodel',
            name='local_path',
        ),
    ]
